name: Delploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy
      run: |
        npm install
        echo "${{ secrets.REACT_APP_API_HOST }} ${{ env.REACT_APP_API_HOST }}"
        npm run deploy
      env:
        REACT_APP_API_HOST: ${{ secrets.REACT_APP_API_HOST }}

    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@releases/v3
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     REACT_APP_API_HOST: ${{ secrets.REACT_APP_API_HOST }}
    #     BRANCH: gh-pages
    #     FOLDER: build