name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        echo "${{ secrets.REACT_APP_API_HOST }} ${{ env.REACT_APP_API_HOST }}"
        npm install
        npm run-script build
      env:
        REACT_APP_API_HOST: ${{ secrets.REACT_APP_API_HOST }}
        NODE_ENV: "production"
        NPM_CONFIG_PRODUCTION: false

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REACT_APP_API_HOST: ${{ secrets.REACT_APP_API_HOST }}
        BRANCH: gh-pages
        FOLDER: build